services:
  - type: web
    name: bg-cleaner
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && python -c "from rembg import new_session; new_session('u2netp')"
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.12"
      - key: SECRET_KEY
        generateValue: true
